### ISSUE TITLE
Cannot send data bigger than internal buffer size.

### ISSUE THREAD

**Issue by urun4m0r1** [DynaSpan/MixedRealityNetworking#3]
When I try to send a packet (an image) larger than the internal buffer.

The program throws an exception:

ReceiveData Error: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.

Have any plans on fixing this problem?
I tried chunking my data but it was bit challenging for me.

**Comment by DynaSpan** [comment]
How big is the image you're sending? 65,535 bytes (~65kB) is the limit for UDP packets. 
I guess I could try to implement a chunking feature but this repo isn't really maintained anymore (I haven't worked with Unity since this repo came online).

What you could do is implement the chunking yourself by pre-pending a byte to the message which would be a counter, and in your receiver you place them in the correct order (based on the counter) and then read the value. However, this would also require to implement a feature for dropped packets and then you're better off looking at TCP streams.

**Comment by urun4m0r1** [comment]
I think you're right.
Since UDP is not suitable for transferring big image data, I will try using TCP for this occasion. Anyway, your code was helpful though. Thank you for your answer.
